# Generated by Django 3.2.8 on 2021-10-21 03:05

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('ffdonations', '0025_auto_20210114_0302'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='donationmodel',
            name='tracking',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict, null=True, verbose_name='Tracking Data'),
        ),
    ]
