# Generated by Django 6.1 on 2026-09-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffdonations', '0027_remove_tiltify_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationmodel',
            old_name='avatarImage',
            new_name='avatar_image',
        ),
        migrations.RenameField(
            model_name='donationmodel',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='participantmodel',
            old_name='avatarImage',
            new_name='avatar_image',
        ),
        migrations.RenameField(
            model_name='participantmodel',
            old_name='campaignDate',
            new_name='campaign_date',
        ),
        migrations.RenameField(
            model_name='participantmodel',
            old_name='campaignName',
            new_name='campaign_name',
        ),
        migrations.RenameField(
            model_name='participantmodel',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='participantmodel',
            old_name='fundraisingGoal',
            new_name='fundraising_goal',
        ),
        migrations.RenameField(
            model_name='participantmodel',
            old_name='isTeamCaptain',
            new_name='is_team_captain',
        ),
        migrations.RenameField(
            model_name='participantmodel',
            old_name='numDonations',
            new_name='num_donations',
        ),
        migrations.RenameField(
            model_name='participantmodel',
            old_name='sumDonations',
            new_name='sum_donations',
        ),
        migrations.RenameField(
            model_name='participantmodel',
            old_name='sumPledges',
            new_name='sum_pledges',
        ),
        migrations.RenameField(
            model_name='teammodel',
            old_name='fundraisingGoal',
            new_name='fundraising_goal',
        ),
        migrations.RenameField(
            model_name='teammodel',
            old_name='numDonations',
            new_name='num_donations',
        ),
        migrations.RenameField(
            model_name='teammodel',
            old_name='sumDonations',
            new_name='sum_donations',
        ),
    ]
