FROM python:3.13-slim AS base

# Setup env
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONFAULTHANDLER=1
RUN apt-get update && apt-get install -y --no-install-recommends python3-lxml python3-dev && rm -rf /var/lib/apt/lists/*

FROM base AS python-deps

# Install compilation dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc git && rm -rf /var/lib/apt/lists/*

# Install python dependencies in /.venv
COPY requirements.txt .

RUN python -m venv /.venv && /.venv/bin/pip install --require-hashes -r requirements.txt


FROM base AS runtime

# Copy virtual env from python-deps stage
COPY --from=python-deps /.venv /.venv
ENV PATH="/.venv/bin:$PATH"

# Create and switch to a new user
RUN useradd --create-home appuser
WORKDIR /home/appuser

# Install application into container
COPY extralifeapi extralifeapi
COPY fforg fforg
COPY ffstream ffstream
COPY ffdonations ffdonations
COPY ffsite ffsite
COPY eventer eventer
COPY evtsignup evtsignup
COPY ffoverlay ffoverlay
COPY ffbot ffbot
COPY ffdiscord ffdiscord
COPY manage.py .
RUN chown -R appuser /home/appuser
USER appuser

CMD [ "celery", "-A", "fforg", "worker", "--autoscale=1,1", "--beat" ]
