FROM python:3-alpine

COPY ./extralifeapi /code/
COPY ./ffdonations /code/
COPY ./fforg /code/
COPY ./ffsite /code/
COPY ./ffsfdc /code/
COPY ./ffstream /code/
COPY ./manage.py /code/
COPY ./Pipfil* /code/

WORKDIR /code

RUN pip install

CMD [ "celery", "-A", "fforg", "worker", "-l", "${CELERY_LOG_LEVEL:-INFO}", "--autoscale=1,1", "--beat" ]