FROM python:3.10-slim as base

# Setup env
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
RUN apt-get update && apt-get install -y --no-install-recommends python3-lxml python3-dev

FROM base AS python-deps

# Install pipenv and compilation dependencies
RUN pip install --upgrade pip
RUN pip install pipenv asdf
RUN apt-get install -y --no-install-recommends gcc git python3-dev

# Install python dependencies in /.venv
COPY Pipfile .
COPY Pipfile.lock .
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy


FROM base AS runtime

# Copy virtual env from python-deps stage
COPY --from=python-deps /.venv /.venv
ENV PATH="/.venv/bin:$PATH"

# Create and switch to a new user
RUN useradd --create-home appuser
WORKDIR /home/appuser

# Install application into container
COPY extralifeapi extralifeapi
COPY fforg fforg
COPY ffstream ffstream
COPY ffdonations ffdonations
COPY ffsite ffsite
COPY eventer eventer
COPY evtsignup evtsignup
COPY ffoverlay ffoverlay
COPY manage.py .

RUN chown -R appuser /home/appuser
USER appuser

RUN /.venv/bin/python manage.py collectstatic --no-input


CMD [ "gunicorn", "fforg.wsgi" ]
