# Generated by Django 5.0.1 on 2024-01-14 23:53
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        HStoreExtension(),
    ]
