# Generated by Django 5.0.1 on 2024-01-15 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evtsignup', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_interest',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.eventinterest')),
            ],
        ),
    ]
