# Generated by Django 5.0.1 on 2024-01-15 00:41

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eventer', '0007_remove_team_admins_remove_team_members_and_more'),
        ('evtsignup', '0003_shiftsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_players', models.PositiveSmallIntegerField(default=1)),
                ('max_players', models.PositiveSmallIntegerField(default=1)),
                ('ideal_players', models.PositiveSmallIntegerField(default=1)),
                ('flags', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('event_interest',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.eventinterest')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.game')),
                ('suggested_players', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ShiftSuggestion',
        ),
    ]
