# Generated by Django 5.0.1 on 2024-01-15 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eventer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='period_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
