# Generated by Django 5.0.1 on 2024-01-15 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('eventer', '0003_event_period_end_event_period_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='period_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='period_start',
            new_name='start',
        ),
    ]
