# Generated by Django 5.0.1 on 2024-01-15 00:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('eventer', '0005_remove_event_end_remove_event_start_eventperiod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventperiod',
            old_name='end',
            new_name='stop',
        ),
    ]
