name: Dev Images

env:
  BUILD_ARGS: ""

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: fragforce-dev
    strategy:
      max-parallel: 4
      matrix:
        dockerfile: [ "web", "worker", "beat" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMG_NAME }}-${{ matrix.dockerfile }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to GitHub Container Registry
        if: env.BUILD_ARGS != '--test'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
      - name: Deploy
        uses: darnfish/watchtower-update@v3.3
        with:
          url: "${{ secrets.WATCHTOWER_URL }}"
          api_token: "${{ secrets.WATCHTOWER_API_TOKEN }}"
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"


